CREATE DATABASE THPTMANAGERMENT

CREATE TABLE SUBJECTT
(
	ID CHAR(10) PRIMARY KEY,
	SUBJECTNAME NVARCHAR(30)
)
CREATE TABLE TEACHER
(
	ID CHAR(10) PRIMARY KEY,
	CCCD NVARCHAR(30) ,
	FULLNAME NVARCHAR(30),
	BIRTH DATE ,
	ADDRESSS NVARCHAR(30),
	PHONE NVARCHAR(10),
	SALARY INT ,
	SUBJECTID CHAR(10) FOREIGN KEY REFERENCES SUBJECTT(ID)
)
CREATE TABLE COURSE
(
	ID CHAR(10) PRIMARY KEY ,
	COURSENAME NVARCHAR(30) ,
	HOMEROOMTEACHERID CHAR(10) FOREIGN KEY REFERENCES TEACHER(ID)
)

CREATE TABLE STUDENT
(
	ID CHAR(10) PRIMARY KEY,
	CCCD NVARCHAR(30) ,
	FULLNAME NVARCHAR(30),
	BIRTH DATE ,
	ADDRESSS NVARCHAR(30),
	PHONE NVARCHAR(10),
	SCHOOLYEAR NVARCHAR(30),
	COURSEID CHAR(10) FOREIGN KEY REFERENCES COURSE(ID) 
)
CREATE TABLE GRADELIST
(
	ID CHAR(10) FOREIGN KEY REFERENCES STUDENT(ID),
	PRIMARY KEY (ID) ,
	MATH DECIMAL(10,2),
	LITERATURE DECIMAL(10,2),
	ENGLISH DECIMAL(10,2),
	PHYSICAL DECIMAL(10,2),
	CHEMISTRY DECIMAL(10,2),
	HISTORY DECIMAL(10,2),
	GEOGRAPHYY DECIMAL(10,2),
	AVGGRADE DECIMAL(10,2)
)